# -*- coding: utf-8 -*-
"""naive_bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPuOgwfRSqGgTF30pJMtWd8OiJIIKRij
"""

import quandl
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

df = quandl.get('WIKI/AMZN')
df.head()

df['Profit'] = np.where(df['Open']<df['Close'], 1, 0)
df = df.drop(columns=['Ex-Dividend', 'Split Ratio'])

X = df.drop(columns=['Profit'])

y = df['Profit']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Accuracy Score: ',model.score(X_test, y_test))
print('Confusion Matrix', confusion_matrix(y_pred, y_test))